version: "3"
services:
  user-service:
    image: kstokely/microchat:latest
    hostname: user-service
    restart: always
    entrypoint: UserService
  message-service:
    image: kstokely/microchat:latest
    hostname: message-service
    restart: always
    entrypoint: MessageService
  friend-recommendation-service:
    image: kstokely/microchat:latest
    hostname: friend-recommendation-service
    restart: always
    entrypoint: FriendRecommendationService
  database-service:
    image: kstokely/microchat:latest
    hostname: databaes-service
    restart: always
    entrypoint: DatabaseService
  user-mongodb:
      image: mongo
      hostname: user-mongodb
      # ports:
      #  - 27023:27017
      restart: always
  
  friend-mongodb:
      image: mongo
      hostname: friend-mongodb
      # ports:
      #- 27023:27018
      restart: always
  
  message-mongodb:
      image: mongo
      hostname: message-mongodb
      # ports:
      #  - 27023:27019
      restart: always
  nginx-thrift:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./nginx_reverse_proxy/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx_reverse_proxy/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gen-lua:/gen-lua