version: "3"
services:
  user-service:
    image: kstokely/microchat:latest
    hostname: user-service
    depends_on: 
      - "user-mongodb"
    restart: always
    entrypoint: UserService
  message-service:
    image: kstokely/microchat:latest
    hostname: message-service
    depends_on: 
      - "message-mongodb"
    restart: always
    entrypoint: MessageService
  friend-recommendation-service:
    image: kstokely/microchat:latest
    hostname: friend-recommendation-service
    depends_on: 
      - "friend-mongodb"
    restart: always
    entrypoint: FriendRecommendationService
  nginx-thrift:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    ports:
      - 8080:8080
    restart: always

user-mongodb:
  image: mongo
  hostname: user-mongodb
  ports:
    - 27023:27017
  restart: always

friend-mongodb:
  image: mongo
  hostname: user-mongodb
  ports:
   - 27023:27018
  restart: always

message-mongodb:
  image: mongo
  hostname: user-mongodb
  ports:
    - 27023:27018
  restart: always

volumes:
   - ./nginx_reverse_proxy/lua-scripts:/usr/local/openresty/nginx/lua-scripts
   - ./nginx_reverse_proxy/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
   - ./gen-lua:/gen-lua